### ISSUE TITLE
Nothing happens when I press 1.

### ISSUE THREAD

**Issue by tybernation** [SpigotMC-Updater-Development/SpigotMC-Updater-Reloaded#7]
Not sure what is happening, but when I press 1 and enter in the Menu.bat file, it doesn't do anything besides adding a line "\SpigotMC-Updater-Reloaded-2.0\tasks\delbt.bat" to the top of the command prompt.

Running Windows 10 if that helps.

**Comment by Legoman99573** [comment]
3.0 is coming out with a rewrite do to the anniversary update breaking most of the `if` Statements

**Comment by Legoman99573** [comment]
3.3 should fix that issue. If not, Let me know and i can reopen your issue ;)
